name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          pattern: awim-*
          path: builds
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: AWiM ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: false
          files: builds/awim-*
